//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOS.WebService.SAPSERVICES_HWYKCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sjyg.com/oa2erp/Z_GM_POST4/if", ConfigurationName="SAPSERVICES_HWYKCS.SI_Z_GM_POST4_OUT")]
    public interface SI_Z_GM_POST4_OUT {
        
        // CODEGEN: 操作 SI_Z_GM_POST_OUT 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTResponse SI_Z_GM_POST_OUT(EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_GM_POST4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPI2017_GM_CODE gOODSMVT_CODEField;
        
        private BAPI2017_GM_HEAD_01 gOODSMVT_HEADERField;
        
        private BAPI2017_GM_ITEM_CREATE[] gOODSMVT_ITEMField;
        
        private BAPIRET2[] rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BAPI2017_GM_CODE GOODSMVT_CODE {
            get {
                return this.gOODSMVT_CODEField;
            }
            set {
                this.gOODSMVT_CODEField = value;
                this.RaisePropertyChanged("GOODSMVT_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BAPI2017_GM_HEAD_01 GOODSMVT_HEADER {
            get {
                return this.gOODSMVT_HEADERField;
            }
            set {
                this.gOODSMVT_HEADERField = value;
                this.RaisePropertyChanged("GOODSMVT_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPI2017_GM_ITEM_CREATE[] GOODSMVT_ITEM {
            get {
                return this.gOODSMVT_ITEMField;
            }
            set {
                this.gOODSMVT_ITEMField = value;
                this.RaisePropertyChanged("GOODSMVT_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
                this.RaisePropertyChanged("RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI2017_GM_CODE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gM_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string GM_CODE {
            get {
                return this.gM_CODEField;
            }
            set {
                this.gM_CODEField = value;
                this.RaisePropertyChanged("GM_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI2017_GM_ITEM_CREATE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATERIALField;
        
        private string pLANTField;
        
        private string sTGE_LOCField;
        
        private string bATCHField;
        
        private string mOVE_TYPEField;
        
        private string sTCK_TYPEField;
        
        private string sPEC_STOCKField;
        
        private string vENDORField;
        
        private string cUSTOMERField;
        
        private string sALES_ORDField;
        
        private string s_ORD_ITEMField;
        
        private string sCHED_LINEField;
        
        private string vAL_TYPEField;
        
        private decimal eNTRY_QNTField;
        
        private bool eNTRY_QNTFieldSpecified;
        
        private string eNTRY_UOMField;
        
        private string eNTRY_UOM_ISOField;
        
        private decimal pO_PR_QNTField;
        
        private bool pO_PR_QNTFieldSpecified;
        
        private string oRDERPR_UNField;
        
        private string oRDERPR_UN_ISOField;
        
        private string pO_NUMBERField;
        
        private string pO_ITEMField;
        
        private string sHIPPINGField;
        
        private string cOMP_SHIPField;
        
        private string nO_MORE_GRField;
        
        private string iTEM_TEXTField;
        
        private string gR_RCPTField;
        
        private string uNLOAD_PTField;
        
        private string cOSTCENTERField;
        
        private string oRDERIDField;
        
        private string oRDER_ITNOField;
        
        private string cALC_MOTIVEField;
        
        private string aSSET_NOField;
        
        private string sUB_NUMBERField;
        
        private string rESERV_NOField;
        
        private string rES_ITEMField;
        
        private string rES_TYPEField;
        
        private string wITHDRAWNField;
        
        private string mOVE_MATField;
        
        private string mOVE_PLANTField;
        
        private string mOVE_STLOCField;
        
        private string mOVE_BATCHField;
        
        private string mOVE_VAL_TYPEField;
        
        private string mVT_INDField;
        
        private string mOVE_REASField;
        
        private string rL_EST_KEYField;
        
        private string rEF_DATEField;
        
        private string cOST_OBJField;
        
        private string pROFIT_SEGM_NOField;
        
        private string pROFIT_CTRField;
        
        private string wBS_ELEMField;
        
        private string nETWORKField;
        
        private string aCTIVITYField;
        
        private string pART_ACCTField;
        
        private decimal aMOUNT_LCField;
        
        private bool aMOUNT_LCFieldSpecified;
        
        private decimal aMOUNT_SVField;
        
        private bool aMOUNT_SVFieldSpecified;
        
        private string rEF_DOC_YRField;
        
        private string rEF_DOCField;
        
        private string rEF_DOC_ITField;
        
        private string eXPIRYDATEField;
        
        private string pROD_DATEField;
        
        private string fUNDField;
        
        private string fUNDS_CTRField;
        
        private string cMMT_ITEMField;
        
        private string vAL_SALES_ORDField;
        
        private string vAL_S_ORD_ITEMField;
        
        private string vAL_WBS_ELEMField;
        
        private string gL_ACCOUNTField;
        
        private string iND_PROPOSE_QUANXField;
        
        private string xSTOBField;
        
        private string eAN_UPCField;
        
        private string dELIV_NUMB_TO_SEARCHField;
        
        private string dELIV_ITEM_TO_SEARCHField;
        
        private string sERIALNO_AUTO_NUMBERASSIGNMENTField;
        
        private string vENDRBATCHField;
        
        private string sTGE_TYPEField;
        
        private string sTGE_BINField;
        
        private decimal sU_PL_STCK_1Field;
        
        private bool sU_PL_STCK_1FieldSpecified;
        
        private decimal sT_UN_QTYY_1Field;
        
        private bool sT_UN_QTYY_1FieldSpecified;
        
        private string sT_UN_QTYY_1_ISOField;
        
        private string uNITTYPE_1Field;
        
        private decimal sU_PL_STCK_2Field;
        
        private bool sU_PL_STCK_2FieldSpecified;
        
        private decimal sT_UN_QTYY_2Field;
        
        private bool sT_UN_QTYY_2FieldSpecified;
        
        private string sT_UN_QTYY_2_ISOField;
        
        private string uNITTYPE_2Field;
        
        private string sTGE_TYPE_PCField;
        
        private string sTGE_BIN_PCField;
        
        private string nO_PST_CHGNTField;
        
        private string gR_NUMBERField;
        
        private string sTGE_TYPE_STField;
        
        private string sTGE_BIN_STField;
        
        private string mATDOC_TR_CANCELField;
        
        private string mATITEM_TR_CANCELField;
        
        private string mATYEAR_TR_CANCELField;
        
        private string nO_TRANSFER_REQField;
        
        private string cO_BUSPROCField;
        
        private string aCTTYPEField;
        
        private string sUPPL_VENDField;
        
        private string mATERIAL_EXTERNALField;
        
        private string mATERIAL_GUIDField;
        
        private string mATERIAL_VERSIONField;
        
        private string mOVE_MAT_EXTERNALField;
        
        private string mOVE_MAT_GUIDField;
        
        private string mOVE_MAT_VERSIONField;
        
        private string fUNC_AREAField;
        
        private string tR_PART_BAField;
        
        private string pAR_COMPCOField;
        
        private string dELIV_NUMBField;
        
        private string dELIV_ITEMField;
        
        private string nB_SLIPSField;
        
        private string nB_SLIPSXField;
        
        private string gR_RCPTXField;
        
        private string uNLOAD_PTXField;
        
        private string sPEC_MVMTField;
        
        private string gRANT_NBRField;
        
        private string cMMT_ITEM_LONGField;
        
        private string fUNC_AREA_LONGField;
        
        private string lINE_IDField;
        
        private string pARENT_IDField;
        
        private string lINE_DEPTHField;
        
        private decimal qUANTITYField;
        
        private bool qUANTITYFieldSpecified;
        
        private string bASE_UOMField;
        
        private string lONGNUMField;
        
        private string bUDGET_PERIODField;
        
        private string eARMARKED_NUMBERField;
        
        private string eARMARKED_ITEMField;
        
        private string sTK_SEGMENTField;
        
        private string mOVE_SEGMENTField;
        
        private string mATERIAL_LONGField;
        
        private string mOVE_MAT_LONGField;
        
        private string sTK_SEG_LONGField;
        
        private string mOV_SEG_LONGField;
        
        private string cREATE_DELIVERYField;
        
        private string wAREHOUSE_EWMField;
        
        private string sTGE_BIN_EWMField;
        
        private string eWM_DIFF_ANAField;
        
        private string sERVICE_DOCField;
        
        private string sERVICE_ITEMField;
        
        private string sERVICE_DOC_TYPEField;
        
        private string sUPPLYAREAField;
        
        private string eWM_INSPUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
                this.RaisePropertyChanged("PLANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string STGE_LOC {
            get {
                return this.sTGE_LOCField;
            }
            set {
                this.sTGE_LOCField = value;
                this.RaisePropertyChanged("STGE_LOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BATCH {
            get {
                return this.bATCHField;
            }
            set {
                this.bATCHField = value;
                this.RaisePropertyChanged("BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MOVE_TYPE {
            get {
                return this.mOVE_TYPEField;
            }
            set {
                this.mOVE_TYPEField = value;
                this.RaisePropertyChanged("MOVE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STCK_TYPE {
            get {
                return this.sTCK_TYPEField;
            }
            set {
                this.sTCK_TYPEField = value;
                this.RaisePropertyChanged("STCK_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SPEC_STOCK {
            get {
                return this.sPEC_STOCKField;
            }
            set {
                this.sPEC_STOCKField = value;
                this.RaisePropertyChanged("SPEC_STOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VENDOR {
            get {
                return this.vENDORField;
            }
            set {
                this.vENDORField = value;
                this.RaisePropertyChanged("VENDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CUSTOMER {
            get {
                return this.cUSTOMERField;
            }
            set {
                this.cUSTOMERField = value;
                this.RaisePropertyChanged("CUSTOMER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SALES_ORD {
            get {
                return this.sALES_ORDField;
            }
            set {
                this.sALES_ORDField = value;
                this.RaisePropertyChanged("SALES_ORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string S_ORD_ITEM {
            get {
                return this.s_ORD_ITEMField;
            }
            set {
                this.s_ORD_ITEMField = value;
                this.RaisePropertyChanged("S_ORD_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SCHED_LINE {
            get {
                return this.sCHED_LINEField;
            }
            set {
                this.sCHED_LINEField = value;
                this.RaisePropertyChanged("SCHED_LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string VAL_TYPE {
            get {
                return this.vAL_TYPEField;
            }
            set {
                this.vAL_TYPEField = value;
                this.RaisePropertyChanged("VAL_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal ENTRY_QNT {
            get {
                return this.eNTRY_QNTField;
            }
            set {
                this.eNTRY_QNTField = value;
                this.RaisePropertyChanged("ENTRY_QNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTRY_QNTSpecified {
            get {
                return this.eNTRY_QNTFieldSpecified;
            }
            set {
                this.eNTRY_QNTFieldSpecified = value;
                this.RaisePropertyChanged("ENTRY_QNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ENTRY_UOM {
            get {
                return this.eNTRY_UOMField;
            }
            set {
                this.eNTRY_UOMField = value;
                this.RaisePropertyChanged("ENTRY_UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ENTRY_UOM_ISO {
            get {
                return this.eNTRY_UOM_ISOField;
            }
            set {
                this.eNTRY_UOM_ISOField = value;
                this.RaisePropertyChanged("ENTRY_UOM_ISO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal PO_PR_QNT {
            get {
                return this.pO_PR_QNTField;
            }
            set {
                this.pO_PR_QNTField = value;
                this.RaisePropertyChanged("PO_PR_QNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PO_PR_QNTSpecified {
            get {
                return this.pO_PR_QNTFieldSpecified;
            }
            set {
                this.pO_PR_QNTFieldSpecified = value;
                this.RaisePropertyChanged("PO_PR_QNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ORDERPR_UN {
            get {
                return this.oRDERPR_UNField;
            }
            set {
                this.oRDERPR_UNField = value;
                this.RaisePropertyChanged("ORDERPR_UN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ORDERPR_UN_ISO {
            get {
                return this.oRDERPR_UN_ISOField;
            }
            set {
                this.oRDERPR_UN_ISOField = value;
                this.RaisePropertyChanged("ORDERPR_UN_ISO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PO_NUMBER {
            get {
                return this.pO_NUMBERField;
            }
            set {
                this.pO_NUMBERField = value;
                this.RaisePropertyChanged("PO_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PO_ITEM {
            get {
                return this.pO_ITEMField;
            }
            set {
                this.pO_ITEMField = value;
                this.RaisePropertyChanged("PO_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SHIPPING {
            get {
                return this.sHIPPINGField;
            }
            set {
                this.sHIPPINGField = value;
                this.RaisePropertyChanged("SHIPPING");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string COMP_SHIP {
            get {
                return this.cOMP_SHIPField;
            }
            set {
                this.cOMP_SHIPField = value;
                this.RaisePropertyChanged("COMP_SHIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string NO_MORE_GR {
            get {
                return this.nO_MORE_GRField;
            }
            set {
                this.nO_MORE_GRField = value;
                this.RaisePropertyChanged("NO_MORE_GR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string ITEM_TEXT {
            get {
                return this.iTEM_TEXTField;
            }
            set {
                this.iTEM_TEXTField = value;
                this.RaisePropertyChanged("ITEM_TEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string GR_RCPT {
            get {
                return this.gR_RCPTField;
            }
            set {
                this.gR_RCPTField = value;
                this.RaisePropertyChanged("GR_RCPT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string UNLOAD_PT {
            get {
                return this.uNLOAD_PTField;
            }
            set {
                this.uNLOAD_PTField = value;
                this.RaisePropertyChanged("UNLOAD_PT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string COSTCENTER {
            get {
                return this.cOSTCENTERField;
            }
            set {
                this.cOSTCENTERField = value;
                this.RaisePropertyChanged("COSTCENTER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string ORDERID {
            get {
                return this.oRDERIDField;
            }
            set {
                this.oRDERIDField = value;
                this.RaisePropertyChanged("ORDERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string ORDER_ITNO {
            get {
                return this.oRDER_ITNOField;
            }
            set {
                this.oRDER_ITNOField = value;
                this.RaisePropertyChanged("ORDER_ITNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CALC_MOTIVE {
            get {
                return this.cALC_MOTIVEField;
            }
            set {
                this.cALC_MOTIVEField = value;
                this.RaisePropertyChanged("CALC_MOTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ASSET_NO {
            get {
                return this.aSSET_NOField;
            }
            set {
                this.aSSET_NOField = value;
                this.RaisePropertyChanged("ASSET_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string SUB_NUMBER {
            get {
                return this.sUB_NUMBERField;
            }
            set {
                this.sUB_NUMBERField = value;
                this.RaisePropertyChanged("SUB_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string RESERV_NO {
            get {
                return this.rESERV_NOField;
            }
            set {
                this.rESERV_NOField = value;
                this.RaisePropertyChanged("RESERV_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string RES_ITEM {
            get {
                return this.rES_ITEMField;
            }
            set {
                this.rES_ITEMField = value;
                this.RaisePropertyChanged("RES_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string RES_TYPE {
            get {
                return this.rES_TYPEField;
            }
            set {
                this.rES_TYPEField = value;
                this.RaisePropertyChanged("RES_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string WITHDRAWN {
            get {
                return this.wITHDRAWNField;
            }
            set {
                this.wITHDRAWNField = value;
                this.RaisePropertyChanged("WITHDRAWN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string MOVE_MAT {
            get {
                return this.mOVE_MATField;
            }
            set {
                this.mOVE_MATField = value;
                this.RaisePropertyChanged("MOVE_MAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string MOVE_PLANT {
            get {
                return this.mOVE_PLANTField;
            }
            set {
                this.mOVE_PLANTField = value;
                this.RaisePropertyChanged("MOVE_PLANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string MOVE_STLOC {
            get {
                return this.mOVE_STLOCField;
            }
            set {
                this.mOVE_STLOCField = value;
                this.RaisePropertyChanged("MOVE_STLOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string MOVE_BATCH {
            get {
                return this.mOVE_BATCHField;
            }
            set {
                this.mOVE_BATCHField = value;
                this.RaisePropertyChanged("MOVE_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string MOVE_VAL_TYPE {
            get {
                return this.mOVE_VAL_TYPEField;
            }
            set {
                this.mOVE_VAL_TYPEField = value;
                this.RaisePropertyChanged("MOVE_VAL_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string MVT_IND {
            get {
                return this.mVT_INDField;
            }
            set {
                this.mVT_INDField = value;
                this.RaisePropertyChanged("MVT_IND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string MOVE_REAS {
            get {
                return this.mOVE_REASField;
            }
            set {
                this.mOVE_REASField = value;
                this.RaisePropertyChanged("MOVE_REAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string RL_EST_KEY {
            get {
                return this.rL_EST_KEYField;
            }
            set {
                this.rL_EST_KEYField = value;
                this.RaisePropertyChanged("RL_EST_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string REF_DATE {
            get {
                return this.rEF_DATEField;
            }
            set {
                this.rEF_DATEField = value;
                this.RaisePropertyChanged("REF_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string COST_OBJ {
            get {
                return this.cOST_OBJField;
            }
            set {
                this.cOST_OBJField = value;
                this.RaisePropertyChanged("COST_OBJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string PROFIT_SEGM_NO {
            get {
                return this.pROFIT_SEGM_NOField;
            }
            set {
                this.pROFIT_SEGM_NOField = value;
                this.RaisePropertyChanged("PROFIT_SEGM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string PROFIT_CTR {
            get {
                return this.pROFIT_CTRField;
            }
            set {
                this.pROFIT_CTRField = value;
                this.RaisePropertyChanged("PROFIT_CTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string WBS_ELEM {
            get {
                return this.wBS_ELEMField;
            }
            set {
                this.wBS_ELEMField = value;
                this.RaisePropertyChanged("WBS_ELEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string NETWORK {
            get {
                return this.nETWORKField;
            }
            set {
                this.nETWORKField = value;
                this.RaisePropertyChanged("NETWORK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string ACTIVITY {
            get {
                return this.aCTIVITYField;
            }
            set {
                this.aCTIVITYField = value;
                this.RaisePropertyChanged("ACTIVITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string PART_ACCT {
            get {
                return this.pART_ACCTField;
            }
            set {
                this.pART_ACCTField = value;
                this.RaisePropertyChanged("PART_ACCT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public decimal AMOUNT_LC {
            get {
                return this.aMOUNT_LCField;
            }
            set {
                this.aMOUNT_LCField = value;
                this.RaisePropertyChanged("AMOUNT_LC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNT_LCSpecified {
            get {
                return this.aMOUNT_LCFieldSpecified;
            }
            set {
                this.aMOUNT_LCFieldSpecified = value;
                this.RaisePropertyChanged("AMOUNT_LCSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public decimal AMOUNT_SV {
            get {
                return this.aMOUNT_SVField;
            }
            set {
                this.aMOUNT_SVField = value;
                this.RaisePropertyChanged("AMOUNT_SV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNT_SVSpecified {
            get {
                return this.aMOUNT_SVFieldSpecified;
            }
            set {
                this.aMOUNT_SVFieldSpecified = value;
                this.RaisePropertyChanged("AMOUNT_SVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string REF_DOC_YR {
            get {
                return this.rEF_DOC_YRField;
            }
            set {
                this.rEF_DOC_YRField = value;
                this.RaisePropertyChanged("REF_DOC_YR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string REF_DOC {
            get {
                return this.rEF_DOCField;
            }
            set {
                this.rEF_DOCField = value;
                this.RaisePropertyChanged("REF_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string REF_DOC_IT {
            get {
                return this.rEF_DOC_ITField;
            }
            set {
                this.rEF_DOC_ITField = value;
                this.RaisePropertyChanged("REF_DOC_IT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string EXPIRYDATE {
            get {
                return this.eXPIRYDATEField;
            }
            set {
                this.eXPIRYDATEField = value;
                this.RaisePropertyChanged("EXPIRYDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string PROD_DATE {
            get {
                return this.pROD_DATEField;
            }
            set {
                this.pROD_DATEField = value;
                this.RaisePropertyChanged("PROD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string FUND {
            get {
                return this.fUNDField;
            }
            set {
                this.fUNDField = value;
                this.RaisePropertyChanged("FUND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string FUNDS_CTR {
            get {
                return this.fUNDS_CTRField;
            }
            set {
                this.fUNDS_CTRField = value;
                this.RaisePropertyChanged("FUNDS_CTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string CMMT_ITEM {
            get {
                return this.cMMT_ITEMField;
            }
            set {
                this.cMMT_ITEMField = value;
                this.RaisePropertyChanged("CMMT_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string VAL_SALES_ORD {
            get {
                return this.vAL_SALES_ORDField;
            }
            set {
                this.vAL_SALES_ORDField = value;
                this.RaisePropertyChanged("VAL_SALES_ORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string VAL_S_ORD_ITEM {
            get {
                return this.vAL_S_ORD_ITEMField;
            }
            set {
                this.vAL_S_ORD_ITEMField = value;
                this.RaisePropertyChanged("VAL_S_ORD_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string VAL_WBS_ELEM {
            get {
                return this.vAL_WBS_ELEMField;
            }
            set {
                this.vAL_WBS_ELEMField = value;
                this.RaisePropertyChanged("VAL_WBS_ELEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string GL_ACCOUNT {
            get {
                return this.gL_ACCOUNTField;
            }
            set {
                this.gL_ACCOUNTField = value;
                this.RaisePropertyChanged("GL_ACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string IND_PROPOSE_QUANX {
            get {
                return this.iND_PROPOSE_QUANXField;
            }
            set {
                this.iND_PROPOSE_QUANXField = value;
                this.RaisePropertyChanged("IND_PROPOSE_QUANX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string XSTOB {
            get {
                return this.xSTOBField;
            }
            set {
                this.xSTOBField = value;
                this.RaisePropertyChanged("XSTOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string EAN_UPC {
            get {
                return this.eAN_UPCField;
            }
            set {
                this.eAN_UPCField = value;
                this.RaisePropertyChanged("EAN_UPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string DELIV_NUMB_TO_SEARCH {
            get {
                return this.dELIV_NUMB_TO_SEARCHField;
            }
            set {
                this.dELIV_NUMB_TO_SEARCHField = value;
                this.RaisePropertyChanged("DELIV_NUMB_TO_SEARCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string DELIV_ITEM_TO_SEARCH {
            get {
                return this.dELIV_ITEM_TO_SEARCHField;
            }
            set {
                this.dELIV_ITEM_TO_SEARCHField = value;
                this.RaisePropertyChanged("DELIV_ITEM_TO_SEARCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string SERIALNO_AUTO_NUMBERASSIGNMENT {
            get {
                return this.sERIALNO_AUTO_NUMBERASSIGNMENTField;
            }
            set {
                this.sERIALNO_AUTO_NUMBERASSIGNMENTField = value;
                this.RaisePropertyChanged("SERIALNO_AUTO_NUMBERASSIGNMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string VENDRBATCH {
            get {
                return this.vENDRBATCHField;
            }
            set {
                this.vENDRBATCHField = value;
                this.RaisePropertyChanged("VENDRBATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string STGE_TYPE {
            get {
                return this.sTGE_TYPEField;
            }
            set {
                this.sTGE_TYPEField = value;
                this.RaisePropertyChanged("STGE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string STGE_BIN {
            get {
                return this.sTGE_BINField;
            }
            set {
                this.sTGE_BINField = value;
                this.RaisePropertyChanged("STGE_BIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public decimal SU_PL_STCK_1 {
            get {
                return this.sU_PL_STCK_1Field;
            }
            set {
                this.sU_PL_STCK_1Field = value;
                this.RaisePropertyChanged("SU_PL_STCK_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SU_PL_STCK_1Specified {
            get {
                return this.sU_PL_STCK_1FieldSpecified;
            }
            set {
                this.sU_PL_STCK_1FieldSpecified = value;
                this.RaisePropertyChanged("SU_PL_STCK_1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=77)]
        public decimal ST_UN_QTYY_1 {
            get {
                return this.sT_UN_QTYY_1Field;
            }
            set {
                this.sT_UN_QTYY_1Field = value;
                this.RaisePropertyChanged("ST_UN_QTYY_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ST_UN_QTYY_1Specified {
            get {
                return this.sT_UN_QTYY_1FieldSpecified;
            }
            set {
                this.sT_UN_QTYY_1FieldSpecified = value;
                this.RaisePropertyChanged("ST_UN_QTYY_1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=78)]
        public string ST_UN_QTYY_1_ISO {
            get {
                return this.sT_UN_QTYY_1_ISOField;
            }
            set {
                this.sT_UN_QTYY_1_ISOField = value;
                this.RaisePropertyChanged("ST_UN_QTYY_1_ISO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=79)]
        public string UNITTYPE_1 {
            get {
                return this.uNITTYPE_1Field;
            }
            set {
                this.uNITTYPE_1Field = value;
                this.RaisePropertyChanged("UNITTYPE_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=80)]
        public decimal SU_PL_STCK_2 {
            get {
                return this.sU_PL_STCK_2Field;
            }
            set {
                this.sU_PL_STCK_2Field = value;
                this.RaisePropertyChanged("SU_PL_STCK_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SU_PL_STCK_2Specified {
            get {
                return this.sU_PL_STCK_2FieldSpecified;
            }
            set {
                this.sU_PL_STCK_2FieldSpecified = value;
                this.RaisePropertyChanged("SU_PL_STCK_2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=81)]
        public decimal ST_UN_QTYY_2 {
            get {
                return this.sT_UN_QTYY_2Field;
            }
            set {
                this.sT_UN_QTYY_2Field = value;
                this.RaisePropertyChanged("ST_UN_QTYY_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ST_UN_QTYY_2Specified {
            get {
                return this.sT_UN_QTYY_2FieldSpecified;
            }
            set {
                this.sT_UN_QTYY_2FieldSpecified = value;
                this.RaisePropertyChanged("ST_UN_QTYY_2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=82)]
        public string ST_UN_QTYY_2_ISO {
            get {
                return this.sT_UN_QTYY_2_ISOField;
            }
            set {
                this.sT_UN_QTYY_2_ISOField = value;
                this.RaisePropertyChanged("ST_UN_QTYY_2_ISO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=83)]
        public string UNITTYPE_2 {
            get {
                return this.uNITTYPE_2Field;
            }
            set {
                this.uNITTYPE_2Field = value;
                this.RaisePropertyChanged("UNITTYPE_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=84)]
        public string STGE_TYPE_PC {
            get {
                return this.sTGE_TYPE_PCField;
            }
            set {
                this.sTGE_TYPE_PCField = value;
                this.RaisePropertyChanged("STGE_TYPE_PC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=85)]
        public string STGE_BIN_PC {
            get {
                return this.sTGE_BIN_PCField;
            }
            set {
                this.sTGE_BIN_PCField = value;
                this.RaisePropertyChanged("STGE_BIN_PC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=86)]
        public string NO_PST_CHGNT {
            get {
                return this.nO_PST_CHGNTField;
            }
            set {
                this.nO_PST_CHGNTField = value;
                this.RaisePropertyChanged("NO_PST_CHGNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=87)]
        public string GR_NUMBER {
            get {
                return this.gR_NUMBERField;
            }
            set {
                this.gR_NUMBERField = value;
                this.RaisePropertyChanged("GR_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=88)]
        public string STGE_TYPE_ST {
            get {
                return this.sTGE_TYPE_STField;
            }
            set {
                this.sTGE_TYPE_STField = value;
                this.RaisePropertyChanged("STGE_TYPE_ST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=89)]
        public string STGE_BIN_ST {
            get {
                return this.sTGE_BIN_STField;
            }
            set {
                this.sTGE_BIN_STField = value;
                this.RaisePropertyChanged("STGE_BIN_ST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=90)]
        public string MATDOC_TR_CANCEL {
            get {
                return this.mATDOC_TR_CANCELField;
            }
            set {
                this.mATDOC_TR_CANCELField = value;
                this.RaisePropertyChanged("MATDOC_TR_CANCEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=91)]
        public string MATITEM_TR_CANCEL {
            get {
                return this.mATITEM_TR_CANCELField;
            }
            set {
                this.mATITEM_TR_CANCELField = value;
                this.RaisePropertyChanged("MATITEM_TR_CANCEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=92)]
        public string MATYEAR_TR_CANCEL {
            get {
                return this.mATYEAR_TR_CANCELField;
            }
            set {
                this.mATYEAR_TR_CANCELField = value;
                this.RaisePropertyChanged("MATYEAR_TR_CANCEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=93)]
        public string NO_TRANSFER_REQ {
            get {
                return this.nO_TRANSFER_REQField;
            }
            set {
                this.nO_TRANSFER_REQField = value;
                this.RaisePropertyChanged("NO_TRANSFER_REQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=94)]
        public string CO_BUSPROC {
            get {
                return this.cO_BUSPROCField;
            }
            set {
                this.cO_BUSPROCField = value;
                this.RaisePropertyChanged("CO_BUSPROC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=95)]
        public string ACTTYPE {
            get {
                return this.aCTTYPEField;
            }
            set {
                this.aCTTYPEField = value;
                this.RaisePropertyChanged("ACTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=96)]
        public string SUPPL_VEND {
            get {
                return this.sUPPL_VENDField;
            }
            set {
                this.sUPPL_VENDField = value;
                this.RaisePropertyChanged("SUPPL_VEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=97)]
        public string MATERIAL_EXTERNAL {
            get {
                return this.mATERIAL_EXTERNALField;
            }
            set {
                this.mATERIAL_EXTERNALField = value;
                this.RaisePropertyChanged("MATERIAL_EXTERNAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=98)]
        public string MATERIAL_GUID {
            get {
                return this.mATERIAL_GUIDField;
            }
            set {
                this.mATERIAL_GUIDField = value;
                this.RaisePropertyChanged("MATERIAL_GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=99)]
        public string MATERIAL_VERSION {
            get {
                return this.mATERIAL_VERSIONField;
            }
            set {
                this.mATERIAL_VERSIONField = value;
                this.RaisePropertyChanged("MATERIAL_VERSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=100)]
        public string MOVE_MAT_EXTERNAL {
            get {
                return this.mOVE_MAT_EXTERNALField;
            }
            set {
                this.mOVE_MAT_EXTERNALField = value;
                this.RaisePropertyChanged("MOVE_MAT_EXTERNAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=101)]
        public string MOVE_MAT_GUID {
            get {
                return this.mOVE_MAT_GUIDField;
            }
            set {
                this.mOVE_MAT_GUIDField = value;
                this.RaisePropertyChanged("MOVE_MAT_GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=102)]
        public string MOVE_MAT_VERSION {
            get {
                return this.mOVE_MAT_VERSIONField;
            }
            set {
                this.mOVE_MAT_VERSIONField = value;
                this.RaisePropertyChanged("MOVE_MAT_VERSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=103)]
        public string FUNC_AREA {
            get {
                return this.fUNC_AREAField;
            }
            set {
                this.fUNC_AREAField = value;
                this.RaisePropertyChanged("FUNC_AREA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=104)]
        public string TR_PART_BA {
            get {
                return this.tR_PART_BAField;
            }
            set {
                this.tR_PART_BAField = value;
                this.RaisePropertyChanged("TR_PART_BA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=105)]
        public string PAR_COMPCO {
            get {
                return this.pAR_COMPCOField;
            }
            set {
                this.pAR_COMPCOField = value;
                this.RaisePropertyChanged("PAR_COMPCO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=106)]
        public string DELIV_NUMB {
            get {
                return this.dELIV_NUMBField;
            }
            set {
                this.dELIV_NUMBField = value;
                this.RaisePropertyChanged("DELIV_NUMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=107)]
        public string DELIV_ITEM {
            get {
                return this.dELIV_ITEMField;
            }
            set {
                this.dELIV_ITEMField = value;
                this.RaisePropertyChanged("DELIV_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=108)]
        public string NB_SLIPS {
            get {
                return this.nB_SLIPSField;
            }
            set {
                this.nB_SLIPSField = value;
                this.RaisePropertyChanged("NB_SLIPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=109)]
        public string NB_SLIPSX {
            get {
                return this.nB_SLIPSXField;
            }
            set {
                this.nB_SLIPSXField = value;
                this.RaisePropertyChanged("NB_SLIPSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=110)]
        public string GR_RCPTX {
            get {
                return this.gR_RCPTXField;
            }
            set {
                this.gR_RCPTXField = value;
                this.RaisePropertyChanged("GR_RCPTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=111)]
        public string UNLOAD_PTX {
            get {
                return this.uNLOAD_PTXField;
            }
            set {
                this.uNLOAD_PTXField = value;
                this.RaisePropertyChanged("UNLOAD_PTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=112)]
        public string SPEC_MVMT {
            get {
                return this.sPEC_MVMTField;
            }
            set {
                this.sPEC_MVMTField = value;
                this.RaisePropertyChanged("SPEC_MVMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=113)]
        public string GRANT_NBR {
            get {
                return this.gRANT_NBRField;
            }
            set {
                this.gRANT_NBRField = value;
                this.RaisePropertyChanged("GRANT_NBR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=114)]
        public string CMMT_ITEM_LONG {
            get {
                return this.cMMT_ITEM_LONGField;
            }
            set {
                this.cMMT_ITEM_LONGField = value;
                this.RaisePropertyChanged("CMMT_ITEM_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=115)]
        public string FUNC_AREA_LONG {
            get {
                return this.fUNC_AREA_LONGField;
            }
            set {
                this.fUNC_AREA_LONGField = value;
                this.RaisePropertyChanged("FUNC_AREA_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=116)]
        public string LINE_ID {
            get {
                return this.lINE_IDField;
            }
            set {
                this.lINE_IDField = value;
                this.RaisePropertyChanged("LINE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=117)]
        public string PARENT_ID {
            get {
                return this.pARENT_IDField;
            }
            set {
                this.pARENT_IDField = value;
                this.RaisePropertyChanged("PARENT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=118)]
        public string LINE_DEPTH {
            get {
                return this.lINE_DEPTHField;
            }
            set {
                this.lINE_DEPTHField = value;
                this.RaisePropertyChanged("LINE_DEPTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=119)]
        public decimal QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
                this.RaisePropertyChanged("QUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QUANTITYSpecified {
            get {
                return this.qUANTITYFieldSpecified;
            }
            set {
                this.qUANTITYFieldSpecified = value;
                this.RaisePropertyChanged("QUANTITYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=120)]
        public string BASE_UOM {
            get {
                return this.bASE_UOMField;
            }
            set {
                this.bASE_UOMField = value;
                this.RaisePropertyChanged("BASE_UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=121)]
        public string LONGNUM {
            get {
                return this.lONGNUMField;
            }
            set {
                this.lONGNUMField = value;
                this.RaisePropertyChanged("LONGNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=122)]
        public string BUDGET_PERIOD {
            get {
                return this.bUDGET_PERIODField;
            }
            set {
                this.bUDGET_PERIODField = value;
                this.RaisePropertyChanged("BUDGET_PERIOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=123)]
        public string EARMARKED_NUMBER {
            get {
                return this.eARMARKED_NUMBERField;
            }
            set {
                this.eARMARKED_NUMBERField = value;
                this.RaisePropertyChanged("EARMARKED_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=124)]
        public string EARMARKED_ITEM {
            get {
                return this.eARMARKED_ITEMField;
            }
            set {
                this.eARMARKED_ITEMField = value;
                this.RaisePropertyChanged("EARMARKED_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=125)]
        public string STK_SEGMENT {
            get {
                return this.sTK_SEGMENTField;
            }
            set {
                this.sTK_SEGMENTField = value;
                this.RaisePropertyChanged("STK_SEGMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=126)]
        public string MOVE_SEGMENT {
            get {
                return this.mOVE_SEGMENTField;
            }
            set {
                this.mOVE_SEGMENTField = value;
                this.RaisePropertyChanged("MOVE_SEGMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=127)]
        public string MATERIAL_LONG {
            get {
                return this.mATERIAL_LONGField;
            }
            set {
                this.mATERIAL_LONGField = value;
                this.RaisePropertyChanged("MATERIAL_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=128)]
        public string MOVE_MAT_LONG {
            get {
                return this.mOVE_MAT_LONGField;
            }
            set {
                this.mOVE_MAT_LONGField = value;
                this.RaisePropertyChanged("MOVE_MAT_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=129)]
        public string STK_SEG_LONG {
            get {
                return this.sTK_SEG_LONGField;
            }
            set {
                this.sTK_SEG_LONGField = value;
                this.RaisePropertyChanged("STK_SEG_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=130)]
        public string MOV_SEG_LONG {
            get {
                return this.mOV_SEG_LONGField;
            }
            set {
                this.mOV_SEG_LONGField = value;
                this.RaisePropertyChanged("MOV_SEG_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=131)]
        public string CREATE_DELIVERY {
            get {
                return this.cREATE_DELIVERYField;
            }
            set {
                this.cREATE_DELIVERYField = value;
                this.RaisePropertyChanged("CREATE_DELIVERY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=132)]
        public string WAREHOUSE_EWM {
            get {
                return this.wAREHOUSE_EWMField;
            }
            set {
                this.wAREHOUSE_EWMField = value;
                this.RaisePropertyChanged("WAREHOUSE_EWM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=133)]
        public string STGE_BIN_EWM {
            get {
                return this.sTGE_BIN_EWMField;
            }
            set {
                this.sTGE_BIN_EWMField = value;
                this.RaisePropertyChanged("STGE_BIN_EWM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=134)]
        public string EWM_DIFF_ANA {
            get {
                return this.eWM_DIFF_ANAField;
            }
            set {
                this.eWM_DIFF_ANAField = value;
                this.RaisePropertyChanged("EWM_DIFF_ANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=135)]
        public string SERVICE_DOC {
            get {
                return this.sERVICE_DOCField;
            }
            set {
                this.sERVICE_DOCField = value;
                this.RaisePropertyChanged("SERVICE_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=136)]
        public string SERVICE_ITEM {
            get {
                return this.sERVICE_ITEMField;
            }
            set {
                this.sERVICE_ITEMField = value;
                this.RaisePropertyChanged("SERVICE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=137)]
        public string SERVICE_DOC_TYPE {
            get {
                return this.sERVICE_DOC_TYPEField;
            }
            set {
                this.sERVICE_DOC_TYPEField = value;
                this.RaisePropertyChanged("SERVICE_DOC_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=138)]
        public string SUPPLYAREA {
            get {
                return this.sUPPLYAREAField;
            }
            set {
                this.sUPPLYAREAField = value;
                this.RaisePropertyChanged("SUPPLYAREA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=139)]
        public string EWM_INSPUUID {
            get {
                return this.eWM_INSPUUIDField;
            }
            set {
                this.eWM_INSPUUIDField = value;
                this.RaisePropertyChanged("EWM_INSPUUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI2017_GM_HEAD_01 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pSTNG_DATEField;
        
        private string dOC_DATEField;
        
        private string rEF_DOC_NOField;
        
        private string bILL_OF_LADINGField;
        
        private string gR_GI_SLIP_NOField;
        
        private string pR_UNAMEField;
        
        private string hEADER_TXTField;
        
        private string vER_GR_GI_SLIPField;
        
        private string vER_GR_GI_SLIPXField;
        
        private string eXT_WMSField;
        
        private string rEF_DOC_NO_LONGField;
        
        private string bILL_OF_LADING_LONGField;
        
        private string bAR_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PSTNG_DATE {
            get {
                return this.pSTNG_DATEField;
            }
            set {
                this.pSTNG_DATEField = value;
                this.RaisePropertyChanged("PSTNG_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_DATE {
            get {
                return this.dOC_DATEField;
            }
            set {
                this.dOC_DATEField = value;
                this.RaisePropertyChanged("DOC_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string REF_DOC_NO {
            get {
                return this.rEF_DOC_NOField;
            }
            set {
                this.rEF_DOC_NOField = value;
                this.RaisePropertyChanged("REF_DOC_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BILL_OF_LADING {
            get {
                return this.bILL_OF_LADINGField;
            }
            set {
                this.bILL_OF_LADINGField = value;
                this.RaisePropertyChanged("BILL_OF_LADING");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string GR_GI_SLIP_NO {
            get {
                return this.gR_GI_SLIP_NOField;
            }
            set {
                this.gR_GI_SLIP_NOField = value;
                this.RaisePropertyChanged("GR_GI_SLIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PR_UNAME {
            get {
                return this.pR_UNAMEField;
            }
            set {
                this.pR_UNAMEField = value;
                this.RaisePropertyChanged("PR_UNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string HEADER_TXT {
            get {
                return this.hEADER_TXTField;
            }
            set {
                this.hEADER_TXTField = value;
                this.RaisePropertyChanged("HEADER_TXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VER_GR_GI_SLIP {
            get {
                return this.vER_GR_GI_SLIPField;
            }
            set {
                this.vER_GR_GI_SLIPField = value;
                this.RaisePropertyChanged("VER_GR_GI_SLIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VER_GR_GI_SLIPX {
            get {
                return this.vER_GR_GI_SLIPXField;
            }
            set {
                this.vER_GR_GI_SLIPXField = value;
                this.RaisePropertyChanged("VER_GR_GI_SLIPX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string EXT_WMS {
            get {
                return this.eXT_WMSField;
            }
            set {
                this.eXT_WMSField = value;
                this.RaisePropertyChanged("EXT_WMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string REF_DOC_NO_LONG {
            get {
                return this.rEF_DOC_NO_LONGField;
            }
            set {
                this.rEF_DOC_NO_LONGField = value;
                this.RaisePropertyChanged("REF_DOC_NO_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BILL_OF_LADING_LONG {
            get {
                return this.bILL_OF_LADING_LONGField;
            }
            set {
                this.bILL_OF_LADING_LONGField = value;
                this.RaisePropertyChanged("BILL_OF_LADING_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string BAR_CODE {
            get {
                return this.bAR_CODEField;
            }
            set {
                this.bAR_CODEField = value;
                this.RaisePropertyChanged("BAR_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_GM_POST4Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATDOCUMENTYEARField;
        
        private string mATERIALDOCUMENTField;
        
        private string rcField;
        
        private BAPI2017_GM_ITEM_CREATE[] gOODSMVT_ITEMField;
        
        private BAPIRET2[] rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATDOCUMENTYEAR {
            get {
                return this.mATDOCUMENTYEARField;
            }
            set {
                this.mATDOCUMENTYEARField = value;
                this.RaisePropertyChanged("MATDOCUMENTYEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIALDOCUMENT {
            get {
                return this.mATERIALDOCUMENTField;
            }
            set {
                this.mATERIALDOCUMENTField = value;
                this.RaisePropertyChanged("MATERIALDOCUMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string RC {
            get {
                return this.rcField;
            }
            set {
                this.rcField = value;
                this.RaisePropertyChanged("RC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPI2017_GM_ITEM_CREATE[] GOODSMVT_ITEM {
            get {
                return this.gOODSMVT_ITEMField;
            }
            set {
                this.gOODSMVT_ITEMField = value;
                this.RaisePropertyChanged("GOODSMVT_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
                this.RaisePropertyChanged("RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Z_GM_POST_OUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EOS.WebService.SAPSERVICES_HWYKCS.Z_GM_POST4 Z_GM_POST4;
        
        public SI_Z_GM_POST_OUTRequest() {
        }
        
        public SI_Z_GM_POST_OUTRequest(EOS.WebService.SAPSERVICES_HWYKCS.Z_GM_POST4 Z_GM_POST4) {
            this.Z_GM_POST4 = Z_GM_POST4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Z_GM_POST_OUTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Z_GM_POST4.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Z_GM_POST4.Response")]
        public EOS.WebService.SAPSERVICES_HWYKCS.Z_GM_POST4Response Z_GM_POST4Response;
        
        public SI_Z_GM_POST_OUTResponse() {
        }
        
        public SI_Z_GM_POST_OUTResponse(EOS.WebService.SAPSERVICES_HWYKCS.Z_GM_POST4Response Z_GM_POST4Response) {
            this.Z_GM_POST4Response = Z_GM_POST4Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_Z_GM_POST4_OUTChannel : EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST4_OUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_Z_GM_POST4_OUTClient : System.ServiceModel.ClientBase<EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST4_OUT>, EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST4_OUT {
        
        public SI_Z_GM_POST4_OUTClient() {
        }
        
        public SI_Z_GM_POST4_OUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_Z_GM_POST4_OUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Z_GM_POST4_OUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Z_GM_POST4_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTResponse EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST4_OUT.SI_Z_GM_POST_OUT(EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTRequest request) {
            return base.Channel.SI_Z_GM_POST_OUT(request);
        }
        
        public EOS.WebService.SAPSERVICES_HWYKCS.Z_GM_POST4Response SI_Z_GM_POST_OUT(EOS.WebService.SAPSERVICES_HWYKCS.Z_GM_POST4 Z_GM_POST4) {
            EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTRequest inValue = new EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTRequest();
            inValue.Z_GM_POST4 = Z_GM_POST4;
            EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST_OUTResponse retVal = ((EOS.WebService.SAPSERVICES_HWYKCS.SI_Z_GM_POST4_OUT)(this)).SI_Z_GM_POST_OUT(inValue);
            return retVal.Z_GM_POST4Response;
        }
    }
}
