//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOS.WebService.MESSERVICES_XBSLCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cost.soap.ws.sunshine.com/", ConfigurationName="MESSERVICES_XBSLCS.RawMaterialFeedingServiceWS")]
    public interface RawMaterialFeedingServiceWS {
        
        // CODEGEN: 操作 doRawMaterialFeeding 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequest))]
        EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingResponse1 doRawMaterialFeeding(EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cost.soap.ws.sunshine.com/")]
    public partial class doRawMaterialFeeding : object, System.ComponentModel.INotifyPropertyChanged {
        
        private rawMaterialFeedingRequest rawMaterialFeedingRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public rawMaterialFeedingRequest rawMaterialFeedingRequest {
            get {
                return this.rawMaterialFeedingRequestField;
            }
            set {
                this.rawMaterialFeedingRequestField = value;
                this.RaisePropertyChanged("rawMaterialFeedingRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cost.soap.ws.sunshine.com/")]
    public partial class rawMaterialFeedingRequest : baseRequest {
        
        private rawMaterialFeedingRowRequest[] rowRequestListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rowRequestList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public rawMaterialFeedingRowRequest[] rowRequestList {
            get {
                return this.rowRequestListField;
            }
            set {
                this.rowRequestListField = value;
                this.RaisePropertyChanged("rowRequestList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cost.soap.ws.sunshine.com/")]
    public partial class rawMaterialFeedingRowRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchField;
        
        private string dateTimeField;
        
        private string itemField;
        
        private string itemMarkField;
        
        private string pulpTypeField;
        
        private string qtyField;
        
        private string shiftField;
        
        private string shiftDateField;
        
        private string storageLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
                this.RaisePropertyChanged("batch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("dateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string itemMark {
            get {
                return this.itemMarkField;
            }
            set {
                this.itemMarkField = value;
                this.RaisePropertyChanged("itemMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string pulpType {
            get {
                return this.pulpTypeField;
            }
            set {
                this.pulpTypeField = value;
                this.RaisePropertyChanged("pulpType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string shift {
            get {
                return this.shiftField;
            }
            set {
                this.shiftField = value;
                this.RaisePropertyChanged("shift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string shiftDate {
            get {
                return this.shiftDateField;
            }
            set {
                this.shiftDateField = value;
                this.RaisePropertyChanged("shiftDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string storageLocation {
            get {
                return this.storageLocationField;
            }
            set {
                this.storageLocationField = value;
                this.RaisePropertyChanged("storageLocation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cost.soap.ws.sunshine.com/")]
    public partial class baseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cost.soap.ws.sunshine.com/")]
    public partial class doRawMaterialFeedingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private baseResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public baseResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(rawMaterialFeedingRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cost.soap.ws.sunshine.com/")]
    public partial class baseRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string siteField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("site");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRawMaterialFeedingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cost.soap.ws.sunshine.com/", Order=0)]
        public EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeeding doRawMaterialFeeding;
        
        public doRawMaterialFeedingRequest() {
        }
        
        public doRawMaterialFeedingRequest(EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeeding doRawMaterialFeeding) {
            this.doRawMaterialFeeding = doRawMaterialFeeding;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRawMaterialFeedingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cost.soap.ws.sunshine.com/", Order=0)]
        public EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingResponse doRawMaterialFeedingResponse;
        
        public doRawMaterialFeedingResponse1() {
        }
        
        public doRawMaterialFeedingResponse1(EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingResponse doRawMaterialFeedingResponse) {
            this.doRawMaterialFeedingResponse = doRawMaterialFeedingResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RawMaterialFeedingServiceWSChannel : EOS.WebService.MESSERVICES_XBSLCS.RawMaterialFeedingServiceWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RawMaterialFeedingServiceWSClient : System.ServiceModel.ClientBase<EOS.WebService.MESSERVICES_XBSLCS.RawMaterialFeedingServiceWS>, EOS.WebService.MESSERVICES_XBSLCS.RawMaterialFeedingServiceWS {
        
        public RawMaterialFeedingServiceWSClient() {
        }
        
        public RawMaterialFeedingServiceWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RawMaterialFeedingServiceWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RawMaterialFeedingServiceWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RawMaterialFeedingServiceWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingResponse1 EOS.WebService.MESSERVICES_XBSLCS.RawMaterialFeedingServiceWS.doRawMaterialFeeding(EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingRequest request) {
            return base.Channel.doRawMaterialFeeding(request);
        }
        
        public EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingResponse doRawMaterialFeeding(EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeeding doRawMaterialFeeding1) {
            EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingRequest inValue = new EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingRequest();
            inValue.doRawMaterialFeeding = doRawMaterialFeeding1;
            EOS.WebService.MESSERVICES_XBSLCS.doRawMaterialFeedingResponse1 retVal = ((EOS.WebService.MESSERVICES_XBSLCS.RawMaterialFeedingServiceWS)(this)).doRawMaterialFeeding(inValue);
            return retVal.doRawMaterialFeedingResponse;
        }
    }
}
