//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOS.WebService.SAPSERVICES_117ZS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sjyg.com/oa2erp/ZFMM117/if", ConfigurationName="SAPSERVICES_117ZS.SI_ZFMM117_OUT")]
    public interface SI_ZFMM117_OUT {
        
        // CODEGEN: 操作 SI_ZFMM117_OUT 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTResponse SI_ZFMM117_OUT(EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFMM117 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_EKGRPField;
        
        private string i_EXTWGField;
        
        private string i_MAKTXField;
        
        private string i_MATKLField;
        
        private string i_MATNRField;
        
        private string i_MTARTField;
        
        private string i_WERKSField;
        
        private ZSMM117[] t_OUTTABField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_EKGRP {
            get {
                return this.i_EKGRPField;
            }
            set {
                this.i_EKGRPField = value;
                this.RaisePropertyChanged("I_EKGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_EXTWG {
            get {
                return this.i_EXTWGField;
            }
            set {
                this.i_EXTWGField = value;
                this.RaisePropertyChanged("I_EXTWG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_MAKTX {
            get {
                return this.i_MAKTXField;
            }
            set {
                this.i_MAKTXField = value;
                this.RaisePropertyChanged("I_MAKTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_MATKL {
            get {
                return this.i_MATKLField;
            }
            set {
                this.i_MATKLField = value;
                this.RaisePropertyChanged("I_MATKL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_MATNR {
            get {
                return this.i_MATNRField;
            }
            set {
                this.i_MATNRField = value;
                this.RaisePropertyChanged("I_MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_MTART {
            get {
                return this.i_MTARTField;
            }
            set {
                this.i_MTARTField = value;
                this.RaisePropertyChanged("I_MTART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_WERKS {
            get {
                return this.i_WERKSField;
            }
            set {
                this.i_WERKSField = value;
                this.RaisePropertyChanged("I_WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSMM117[] T_OUTTAB {
            get {
                return this.t_OUTTABField;
            }
            set {
                this.t_OUTTABField = value;
                this.RaisePropertyChanged("T_OUTTAB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSMM117 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATNRField;
        
        private string mAKTXField;
        
        private string mATKLField;
        
        private string eXTWGField;
        
        private string mTARTField;
        
        private string eKGRPField;
        
        private string wERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
                this.RaisePropertyChanged("MAKTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATKL {
            get {
                return this.mATKLField;
            }
            set {
                this.mATKLField = value;
                this.RaisePropertyChanged("MATKL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EXTWG {
            get {
                return this.eXTWGField;
            }
            set {
                this.eXTWGField = value;
                this.RaisePropertyChanged("EXTWG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MTART {
            get {
                return this.mTARTField;
            }
            set {
                this.mTARTField = value;
                this.RaisePropertyChanged("MTART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
                this.RaisePropertyChanged("EKGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFMM117Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSMM117[] t_OUTTABField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSMM117[] T_OUTTAB {
            get {
                return this.t_OUTTABField;
            }
            set {
                this.t_OUTTABField = value;
                this.RaisePropertyChanged("T_OUTTAB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZFMM117_OUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EOS.WebService.SAPSERVICES_117ZS.ZFMM117 ZFMM117;
        
        public SI_ZFMM117_OUTRequest() {
        }
        
        public SI_ZFMM117_OUTRequest(EOS.WebService.SAPSERVICES_117ZS.ZFMM117 ZFMM117) {
            this.ZFMM117 = ZFMM117;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZFMM117_OUTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZFMM117.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZFMM117.Response")]
        public EOS.WebService.SAPSERVICES_117ZS.ZFMM117Response ZFMM117Response;
        
        public SI_ZFMM117_OUTResponse() {
        }
        
        public SI_ZFMM117_OUTResponse(EOS.WebService.SAPSERVICES_117ZS.ZFMM117Response ZFMM117Response) {
            this.ZFMM117Response = ZFMM117Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZFMM117_OUTChannel : EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZFMM117_OUTClient : System.ServiceModel.ClientBase<EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUT>, EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUT {
        
        public SI_ZFMM117_OUTClient() {
        }
        
        public SI_ZFMM117_OUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZFMM117_OUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZFMM117_OUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZFMM117_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTResponse EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUT.SI_ZFMM117_OUT(EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTRequest request) {
            return base.Channel.SI_ZFMM117_OUT(request);
        }
        
        public EOS.WebService.SAPSERVICES_117ZS.ZFMM117Response SI_ZFMM117_OUT(EOS.WebService.SAPSERVICES_117ZS.ZFMM117 ZFMM117) {
            EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTRequest inValue = new EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTRequest();
            inValue.ZFMM117 = ZFMM117;
            EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUTResponse retVal = ((EOS.WebService.SAPSERVICES_117ZS.SI_ZFMM117_OUT)(this)).SI_ZFMM117_OUT(inValue);
            return retVal.ZFMM117Response;
        }
    }
}
