//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOS.WebService.SAPSERVICES_PURCHASE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sjyg.com/mes2erp/Z_ME_OAPURCHASE/if", ConfigurationName="SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASE")]
    public interface SI_Z_ME_OAPURCHASE {
        
        // CODEGEN: 操作 SI_Z_ME_OAPURCHASE 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASEResponse SI_Z_ME_OAPURCHASE(EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_ME_OAPURCHASE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZTTQM001[] t_ZTTQM001Field;
        
        private ZTTQM002[] t_ZTTQM002Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZTTQM001[] T_ZTTQM001 {
            get {
                return this.t_ZTTQM001Field;
            }
            set {
                this.t_ZTTQM001Field = value;
                this.RaisePropertyChanged("T_ZTTQM001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZTTQM002[] T_ZTTQM002 {
            get {
                return this.t_ZTTQM002Field;
            }
            set {
                this.t_ZTTQM002Field = value;
                this.RaisePropertyChanged("T_ZTTQM002");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZTTQM001 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string wERKSField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string mATNRField;
        
        private string fLOW_CODEField;
        
        private string mBLNRField;
        
        private string tASK_TYPEField;
        
        private string iNSPSAMPLEField;
        
        private string iNSPECTION_TYPEField;
        
        private string lADING_NUMBERField;
        
        private string iC_NUMBERField;
        
        private string cHARGField;
        
        private string pRUEFLOSField;
        
        private string iC_WBNUMBERField;
        
        private string tASK_STATUSField;
        
        private string mAKTXField;
        
        private string pOUND_ORDERField;
        
        private string dELIVERY_DATEField;
        
        private string cLOSE_REASONField;
        
        private string sYNCHRONOUSField;
        
        private string eXPLANATIONField;
        
        private string rESULT_JUDGEField;
        
        private string pROCESS_JUDGEField;
        
        private string iNSPECT_START_TIMEField;
        
        private string iNSPECT_END_TIMEField;
        
        private string iNSPECTORField;
        
        private string cREATED_USERField;
        
        private string cREATED_DATE_TIMEField;
        
        private string cONFIRMED_USERField;
        
        private string cONFIRMED_DATE_TIMEField;
        
        private string mODIFIED_USERField;
        
        private string mODIFIED_DATE_TIMEField;
        
        private string sTATUSField;
        
        private string mESSAGEField;
        
        private string zRETURNField;
        
        private string lONG_MATERIALField;
        
        private double gROSS_WEIGHTField;
        
        private bool gROSS_WEIGHTFieldSpecified;
        
        private string sTOCK_LOCATIONField;
        
        private string pACKAGESField;
        
        private string bUYERField;
        
        private string iTEM_LINEField;
        
        private string aCCEPTANCEField;
        
        private string aCTUAL_UCTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
                this.RaisePropertyChanged("EBELP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FLOW_CODE {
            get {
                return this.fLOW_CODEField;
            }
            set {
                this.fLOW_CODEField = value;
                this.RaisePropertyChanged("FLOW_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MBLNR {
            get {
                return this.mBLNRField;
            }
            set {
                this.mBLNRField = value;
                this.RaisePropertyChanged("MBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TASK_TYPE {
            get {
                return this.tASK_TYPEField;
            }
            set {
                this.tASK_TYPEField = value;
                this.RaisePropertyChanged("TASK_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string INSPSAMPLE {
            get {
                return this.iNSPSAMPLEField;
            }
            set {
                this.iNSPSAMPLEField = value;
                this.RaisePropertyChanged("INSPSAMPLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string INSPECTION_TYPE {
            get {
                return this.iNSPECTION_TYPEField;
            }
            set {
                this.iNSPECTION_TYPEField = value;
                this.RaisePropertyChanged("INSPECTION_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string LADING_NUMBER {
            get {
                return this.lADING_NUMBERField;
            }
            set {
                this.lADING_NUMBERField = value;
                this.RaisePropertyChanged("LADING_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string IC_NUMBER {
            get {
                return this.iC_NUMBERField;
            }
            set {
                this.iC_NUMBERField = value;
                this.RaisePropertyChanged("IC_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CHARG {
            get {
                return this.cHARGField;
            }
            set {
                this.cHARGField = value;
                this.RaisePropertyChanged("CHARG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PRUEFLOS {
            get {
                return this.pRUEFLOSField;
            }
            set {
                this.pRUEFLOSField = value;
                this.RaisePropertyChanged("PRUEFLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string IC_WBNUMBER {
            get {
                return this.iC_WBNUMBERField;
            }
            set {
                this.iC_WBNUMBERField = value;
                this.RaisePropertyChanged("IC_WBNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string TASK_STATUS {
            get {
                return this.tASK_STATUSField;
            }
            set {
                this.tASK_STATUSField = value;
                this.RaisePropertyChanged("TASK_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
                this.RaisePropertyChanged("MAKTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string POUND_ORDER {
            get {
                return this.pOUND_ORDERField;
            }
            set {
                this.pOUND_ORDERField = value;
                this.RaisePropertyChanged("POUND_ORDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string DELIVERY_DATE {
            get {
                return this.dELIVERY_DATEField;
            }
            set {
                this.dELIVERY_DATEField = value;
                this.RaisePropertyChanged("DELIVERY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CLOSE_REASON {
            get {
                return this.cLOSE_REASONField;
            }
            set {
                this.cLOSE_REASONField = value;
                this.RaisePropertyChanged("CLOSE_REASON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SYNCHRONOUS {
            get {
                return this.sYNCHRONOUSField;
            }
            set {
                this.sYNCHRONOUSField = value;
                this.RaisePropertyChanged("SYNCHRONOUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string EXPLANATION {
            get {
                return this.eXPLANATIONField;
            }
            set {
                this.eXPLANATIONField = value;
                this.RaisePropertyChanged("EXPLANATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string RESULT_JUDGE {
            get {
                return this.rESULT_JUDGEField;
            }
            set {
                this.rESULT_JUDGEField = value;
                this.RaisePropertyChanged("RESULT_JUDGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string PROCESS_JUDGE {
            get {
                return this.pROCESS_JUDGEField;
            }
            set {
                this.pROCESS_JUDGEField = value;
                this.RaisePropertyChanged("PROCESS_JUDGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string INSPECT_START_TIME {
            get {
                return this.iNSPECT_START_TIMEField;
            }
            set {
                this.iNSPECT_START_TIMEField = value;
                this.RaisePropertyChanged("INSPECT_START_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string INSPECT_END_TIME {
            get {
                return this.iNSPECT_END_TIMEField;
            }
            set {
                this.iNSPECT_END_TIMEField = value;
                this.RaisePropertyChanged("INSPECT_END_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string INSPECTOR {
            get {
                return this.iNSPECTORField;
            }
            set {
                this.iNSPECTORField = value;
                this.RaisePropertyChanged("INSPECTOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string CREATED_USER {
            get {
                return this.cREATED_USERField;
            }
            set {
                this.cREATED_USERField = value;
                this.RaisePropertyChanged("CREATED_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string CREATED_DATE_TIME {
            get {
                return this.cREATED_DATE_TIMEField;
            }
            set {
                this.cREATED_DATE_TIMEField = value;
                this.RaisePropertyChanged("CREATED_DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string CONFIRMED_USER {
            get {
                return this.cONFIRMED_USERField;
            }
            set {
                this.cONFIRMED_USERField = value;
                this.RaisePropertyChanged("CONFIRMED_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string CONFIRMED_DATE_TIME {
            get {
                return this.cONFIRMED_DATE_TIMEField;
            }
            set {
                this.cONFIRMED_DATE_TIMEField = value;
                this.RaisePropertyChanged("CONFIRMED_DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string MODIFIED_USER {
            get {
                return this.mODIFIED_USERField;
            }
            set {
                this.mODIFIED_USERField = value;
                this.RaisePropertyChanged("MODIFIED_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string MODIFIED_DATE_TIME {
            get {
                return this.mODIFIED_DATE_TIMEField;
            }
            set {
                this.mODIFIED_DATE_TIMEField = value;
                this.RaisePropertyChanged("MODIFIED_DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string ZRETURN {
            get {
                return this.zRETURNField;
            }
            set {
                this.zRETURNField = value;
                this.RaisePropertyChanged("ZRETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string LONG_MATERIAL {
            get {
                return this.lONG_MATERIALField;
            }
            set {
                this.lONG_MATERIALField = value;
                this.RaisePropertyChanged("LONG_MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public double GROSS_WEIGHT {
            get {
                return this.gROSS_WEIGHTField;
            }
            set {
                this.gROSS_WEIGHTField = value;
                this.RaisePropertyChanged("GROSS_WEIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROSS_WEIGHTSpecified {
            get {
                return this.gROSS_WEIGHTFieldSpecified;
            }
            set {
                this.gROSS_WEIGHTFieldSpecified = value;
                this.RaisePropertyChanged("GROSS_WEIGHTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string STOCK_LOCATION {
            get {
                return this.sTOCK_LOCATIONField;
            }
            set {
                this.sTOCK_LOCATIONField = value;
                this.RaisePropertyChanged("STOCK_LOCATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string PACKAGES {
            get {
                return this.pACKAGESField;
            }
            set {
                this.pACKAGESField = value;
                this.RaisePropertyChanged("PACKAGES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string BUYER {
            get {
                return this.bUYERField;
            }
            set {
                this.bUYERField = value;
                this.RaisePropertyChanged("BUYER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string ITEM_LINE {
            get {
                return this.iTEM_LINEField;
            }
            set {
                this.iTEM_LINEField = value;
                this.RaisePropertyChanged("ITEM_LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string ACCEPTANCE {
            get {
                return this.aCCEPTANCEField;
            }
            set {
                this.aCCEPTANCEField = value;
                this.RaisePropertyChanged("ACCEPTANCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string ACTUAL_UCTION {
            get {
                return this.aCTUAL_UCTIONField;
            }
            set {
                this.aCTUAL_UCTIONField = value;
                this.RaisePropertyChanged("ACTUAL_UCTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZTTQM002 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string wERKSField;
        
        private string pRUEFLOSField;
        
        private string iNSPCHARField;
        
        private string vERWMERKMField;
        
        private string iNSPSAMPLEField;
        
        private string cHARGField;
        
        private string lADING_NUMBERField;
        
        private string iC_NUMBERField;
        
        private string tASK_RESULTField;
        
        private string tASK_STATUSField;
        
        private string iNSPECT_START_TIMEField;
        
        private string iNSPECT_END_TIMEField;
        
        private string iNSPECTORField;
        
        private string cREATED_USERField;
        
        private string cREATED_DATE_TIMEField;
        
        private string cONFIRMED_USERField;
        
        private string cONFIRMED_DATE_TIMEField;
        
        private string mODIFIED_USERField;
        
        private string mODIFIED_DATE_TIMEField;
        
        private string rESULT_JUDGEField;
        
        private decimal zMAXField;
        
        private bool zMAXFieldSpecified;
        
        private decimal zMINField;
        
        private bool zMINFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PRUEFLOS {
            get {
                return this.pRUEFLOSField;
            }
            set {
                this.pRUEFLOSField = value;
                this.RaisePropertyChanged("PRUEFLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string INSPCHAR {
            get {
                return this.iNSPCHARField;
            }
            set {
                this.iNSPCHARField = value;
                this.RaisePropertyChanged("INSPCHAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string VERWMERKM {
            get {
                return this.vERWMERKMField;
            }
            set {
                this.vERWMERKMField = value;
                this.RaisePropertyChanged("VERWMERKM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string INSPSAMPLE {
            get {
                return this.iNSPSAMPLEField;
            }
            set {
                this.iNSPSAMPLEField = value;
                this.RaisePropertyChanged("INSPSAMPLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CHARG {
            get {
                return this.cHARGField;
            }
            set {
                this.cHARGField = value;
                this.RaisePropertyChanged("CHARG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string LADING_NUMBER {
            get {
                return this.lADING_NUMBERField;
            }
            set {
                this.lADING_NUMBERField = value;
                this.RaisePropertyChanged("LADING_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IC_NUMBER {
            get {
                return this.iC_NUMBERField;
            }
            set {
                this.iC_NUMBERField = value;
                this.RaisePropertyChanged("IC_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TASK_RESULT {
            get {
                return this.tASK_RESULTField;
            }
            set {
                this.tASK_RESULTField = value;
                this.RaisePropertyChanged("TASK_RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TASK_STATUS {
            get {
                return this.tASK_STATUSField;
            }
            set {
                this.tASK_STATUSField = value;
                this.RaisePropertyChanged("TASK_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string INSPECT_START_TIME {
            get {
                return this.iNSPECT_START_TIMEField;
            }
            set {
                this.iNSPECT_START_TIMEField = value;
                this.RaisePropertyChanged("INSPECT_START_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string INSPECT_END_TIME {
            get {
                return this.iNSPECT_END_TIMEField;
            }
            set {
                this.iNSPECT_END_TIMEField = value;
                this.RaisePropertyChanged("INSPECT_END_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string INSPECTOR {
            get {
                return this.iNSPECTORField;
            }
            set {
                this.iNSPECTORField = value;
                this.RaisePropertyChanged("INSPECTOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CREATED_USER {
            get {
                return this.cREATED_USERField;
            }
            set {
                this.cREATED_USERField = value;
                this.RaisePropertyChanged("CREATED_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CREATED_DATE_TIME {
            get {
                return this.cREATED_DATE_TIMEField;
            }
            set {
                this.cREATED_DATE_TIMEField = value;
                this.RaisePropertyChanged("CREATED_DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string CONFIRMED_USER {
            get {
                return this.cONFIRMED_USERField;
            }
            set {
                this.cONFIRMED_USERField = value;
                this.RaisePropertyChanged("CONFIRMED_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CONFIRMED_DATE_TIME {
            get {
                return this.cONFIRMED_DATE_TIMEField;
            }
            set {
                this.cONFIRMED_DATE_TIMEField = value;
                this.RaisePropertyChanged("CONFIRMED_DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string MODIFIED_USER {
            get {
                return this.mODIFIED_USERField;
            }
            set {
                this.mODIFIED_USERField = value;
                this.RaisePropertyChanged("MODIFIED_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string MODIFIED_DATE_TIME {
            get {
                return this.mODIFIED_DATE_TIMEField;
            }
            set {
                this.mODIFIED_DATE_TIMEField = value;
                this.RaisePropertyChanged("MODIFIED_DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string RESULT_JUDGE {
            get {
                return this.rESULT_JUDGEField;
            }
            set {
                this.rESULT_JUDGEField = value;
                this.RaisePropertyChanged("RESULT_JUDGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal ZMAX {
            get {
                return this.zMAXField;
            }
            set {
                this.zMAXField = value;
                this.RaisePropertyChanged("ZMAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZMAXSpecified {
            get {
                return this.zMAXFieldSpecified;
            }
            set {
                this.zMAXFieldSpecified = value;
                this.RaisePropertyChanged("ZMAXSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public decimal ZMIN {
            get {
                return this.zMINField;
            }
            set {
                this.zMINField = value;
                this.RaisePropertyChanged("ZMIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZMINSpecified {
            get {
                return this.zMINFieldSpecified;
            }
            set {
                this.zMINFieldSpecified = value;
                this.RaisePropertyChanged("ZMINSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_ME_OAPURCHASEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e_CODEField;
        
        private string e_MESSAGEField;
        
        private ZTTQM001[] t_ZTTQM001Field;
        
        private ZTTQM002[] t_ZTTQM002Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_CODE {
            get {
                return this.e_CODEField;
            }
            set {
                this.e_CODEField = value;
                this.RaisePropertyChanged("E_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_MESSAGE {
            get {
                return this.e_MESSAGEField;
            }
            set {
                this.e_MESSAGEField = value;
                this.RaisePropertyChanged("E_MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZTTQM001[] T_ZTTQM001 {
            get {
                return this.t_ZTTQM001Field;
            }
            set {
                this.t_ZTTQM001Field = value;
                this.RaisePropertyChanged("T_ZTTQM001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZTTQM002[] T_ZTTQM002 {
            get {
                return this.t_ZTTQM002Field;
            }
            set {
                this.t_ZTTQM002Field = value;
                this.RaisePropertyChanged("T_ZTTQM002");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Z_ME_OAPURCHASERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public EOS.WebService.SAPSERVICES_PURCHASE.Z_ME_OAPURCHASE Z_ME_OAPURCHASE;
        
        public SI_Z_ME_OAPURCHASERequest() {
        }
        
        public SI_Z_ME_OAPURCHASERequest(EOS.WebService.SAPSERVICES_PURCHASE.Z_ME_OAPURCHASE Z_ME_OAPURCHASE) {
            this.Z_ME_OAPURCHASE = Z_ME_OAPURCHASE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Z_ME_OAPURCHASEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Z_ME_OAPURCHASE.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Z_ME_OAPURCHASE.Response")]
        public EOS.WebService.SAPSERVICES_PURCHASE.Z_ME_OAPURCHASEResponse Z_ME_OAPURCHASEResponse;
        
        public SI_Z_ME_OAPURCHASEResponse() {
        }
        
        public SI_Z_ME_OAPURCHASEResponse(EOS.WebService.SAPSERVICES_PURCHASE.Z_ME_OAPURCHASEResponse Z_ME_OAPURCHASEResponse) {
            this.Z_ME_OAPURCHASEResponse = Z_ME_OAPURCHASEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_Z_ME_OAPURCHASEChannel : EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_Z_ME_OAPURCHASEClient : System.ServiceModel.ClientBase<EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASE>, EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASE {
        
        public SI_Z_ME_OAPURCHASEClient() {
        }
        
        public SI_Z_ME_OAPURCHASEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_Z_ME_OAPURCHASEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Z_ME_OAPURCHASEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Z_ME_OAPURCHASEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASEResponse EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASE.SI_Z_ME_OAPURCHASE(EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASERequest request) {
            return base.Channel.SI_Z_ME_OAPURCHASE(request);
        }
        
        public EOS.WebService.SAPSERVICES_PURCHASE.Z_ME_OAPURCHASEResponse SI_Z_ME_OAPURCHASE(EOS.WebService.SAPSERVICES_PURCHASE.Z_ME_OAPURCHASE Z_ME_OAPURCHASE) {
            EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASERequest inValue = new EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASERequest();
            inValue.Z_ME_OAPURCHASE = Z_ME_OAPURCHASE;
            EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASEResponse retVal = ((EOS.WebService.SAPSERVICES_PURCHASE.SI_Z_ME_OAPURCHASE)(this)).SI_Z_ME_OAPURCHASE(inValue);
            return retVal.Z_ME_OAPURCHASEResponse;
        }
    }
}
