//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.81.0。
// 
namespace EOS.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "RawMaterialFeedingServiceWSBinding", Namespace = "http://cost.soap.ws.sunshine.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseRequest))]
    public partial class RawMaterialFeedingServiceWSService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback doRawMaterialFeedingOperationCompleted;

        /// <remarks/>
        public RawMaterialFeedingServiceWSService()
        {
             this.Url = ConfigurationManager.AppSettings["MESDJURL"].ToString(); //"https://sjygme.sunshinepaper.com.cn:44300/webservicewar/RawMaterialFeedingServiceWSService";
        }

        /// <remarks/>
        public event doRawMaterialFeedingCompletedEventHandler doRawMaterialFeedingCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("doRawMaterialFeedingResponse", Namespace = "http://cost.soap.ws.sunshine.com/")]
        public doRawMaterialFeedingResponse doRawMaterialFeeding([System.Xml.Serialization.XmlElementAttribute("doRawMaterialFeeding", Namespace = "http://cost.soap.ws.sunshine.com/")] doRawMaterialFeeding doRawMaterialFeeding1)
        {
            object[] results = this.Invoke("doRawMaterialFeeding", new object[] {
                        doRawMaterialFeeding1});
            return ((doRawMaterialFeedingResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegindoRawMaterialFeeding(doRawMaterialFeeding doRawMaterialFeeding1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("doRawMaterialFeeding", new object[] {
                        doRawMaterialFeeding1}, callback, asyncState);
        }

        /// <remarks/>
        public doRawMaterialFeedingResponse EnddoRawMaterialFeeding(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((doRawMaterialFeedingResponse)(results[0]));
        }

        /// <remarks/>
        public void doRawMaterialFeedingAsync(doRawMaterialFeeding doRawMaterialFeeding1)
        {
            this.doRawMaterialFeedingAsync(doRawMaterialFeeding1, null);
        }

        /// <remarks/>
        public void doRawMaterialFeedingAsync(doRawMaterialFeeding doRawMaterialFeeding1, object userState)
        {
            if ((this.doRawMaterialFeedingOperationCompleted == null))
            {
                this.doRawMaterialFeedingOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoRawMaterialFeedingOperationCompleted);
            }
            this.InvokeAsync("doRawMaterialFeeding", new object[] {
                        doRawMaterialFeeding1}, this.doRawMaterialFeedingOperationCompleted, userState);
        }

        private void OndoRawMaterialFeedingOperationCompleted(object arg)
        {
            if ((this.doRawMaterialFeedingCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doRawMaterialFeedingCompleted(this, new doRawMaterialFeedingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cost.soap.ws.sunshine.com/")]
    public partial class doRawMaterialFeeding
    {

        private rawMaterialFeedingRequest rawMaterialFeedingRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rawMaterialFeedingRequest rawMaterialFeedingRequest
        {
            get
            {
                return this.rawMaterialFeedingRequestField;
            }
            set
            {
                this.rawMaterialFeedingRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cost.soap.ws.sunshine.com/")]
    public partial class rawMaterialFeedingRequest : baseRequest
    {

        private rawMaterialFeedingRowRequest[] rowRequestListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rowRequestList", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public rawMaterialFeedingRowRequest[] rowRequestList
        {
            get
            {
                return this.rowRequestListField;
            }
            set
            {
                this.rowRequestListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cost.soap.ws.sunshine.com/")]
    public partial class rawMaterialFeedingRowRequest
    {

        private string batchField;

        private string dateTimeField;

        private string itemField;

        private string itemMarkField;

        private string pulpTypeField;

        private string qtyField;

        private string shiftField;

        private string shiftDateField;

        private string storageLocationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string itemMark
        {
            get
            {
                return this.itemMarkField;
            }
            set
            {
                this.itemMarkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pulpType
        {
            get
            {
                return this.pulpTypeField;
            }
            set
            {
                this.pulpTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shift
        {
            get
            {
                return this.shiftField;
            }
            set
            {
                this.shiftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shiftDate
        {
            get
            {
                return this.shiftDateField;
            }
            set
            {
                this.shiftDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string storageLocation
        {
            get
            {
                return this.storageLocationField;
            }
            set
            {
                this.storageLocationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cost.soap.ws.sunshine.com/")]
    public partial class baseResponse
    {

        private long codeField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cost.soap.ws.sunshine.com/")]
    public partial class doRawMaterialFeedingResponse
    {

        private baseResponse returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public baseResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(rawMaterialFeedingRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cost.soap.ws.sunshine.com/")]
    public partial class baseRequest
    {

        private string siteField;

        private string userIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void doRawMaterialFeedingCompletedEventHandler(object sender, doRawMaterialFeedingCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doRawMaterialFeedingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal doRawMaterialFeedingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public doRawMaterialFeedingResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((doRawMaterialFeedingResponse)(this.results[0]));
            }
        }
    }
}
